### ISSUE TITLE
[Import API fail]DLL load failed

### ISSUE THREAD

**Issue by Yaccoub** [InnovizTechnologies/InnovizAPI#4]
After following all the instructions for Windows and installing the API successfully I get the following error when trying to run an example : 

ImportError: DLL load failed: The specified module could not be found 

If anyone could help me. Thank you very much

**Comment by Innoviz-Tech-Support** [comment]
Hi Yaccoub,
Which of the windows examples are you trying to run?  The C++ demo program?  Or one of the sample Python scripts?

If you're using python, make sure that you have all the prerequisite requirements.
These 2 python modules need to be installed:
-pybind11
-numpy

In addition, you'll need to install cpp build tools, which can be done from the link below.
https://visualstudio.microsoft.com/visual-cpp-build-tools/

I hope this helps.

**Comment by Yaccoub** [comment]
Thank you for your quick response. I'm trying to run the python example get_object. I installed all of the prerequisites and followed the instructions but still get this error message

**Comment by Innoviz-Tech-Support** [comment]
I tested this script again and confirm it works.  Which module is it telling you cannot be found, innopy?
Did you clone/download the entire API package?

**Comment by mezghanni-m** [comment]
I'm facing the same issue using the API on Windows 10: 
Traceback (most recent call last):
  File "C:/Users/InnovizAPI/examples/python/recording_get_objects.py", line 17, in <module>
    from innopy.api import FileReader, FrameDataAttributes, GrabType
ImportError: ImportError: DLL load failed: The specified module could not be found

**Comment by Yaccoub** [comment]
Hello all, 
Running Dependencies (An open-source modern Dependency Walker) I noticed that wpcap.dll was missing so installing [WinPcap](https://www.winpcap.org/install/default.htm) has solved my problem.

**Comment by Innoviz-Tech-Support** [comment]
You're right! I thought it was already listed in the requirements.  Winpcap or npcap is needed as well.
[https://nmap.org/npcap/]
Thanks for bringing this to our attention.  The requirements will be updated.
