### ISSUE TITLE
Cannot Run ROS Examples on Ubuntu 18.04

### ISSUE THREAD

**Issue by Yaccoub** [InnovizTechnologies/InnovizAPI#5]
Hello, 

While trying to run the ROS examples on Ubuntu 18.04 I faced the following issue: 

`ERROR: cannot launch node of type [innoviz_ros/run_rviz.sh]: Cannot locate node of type [run_rviz.sh] in package [innoviz_ros]. Make sure file exists in package path and permission is set to executable (chmod +x) `

It's worth mentioning that while trying to build the c++ examples using `cmake -G "Unix Makefiles" -B "build"`  I get the following error ` CMake Error: The source directory "/home/InnovizAPI/examples/cpp/build" does not exist`. So I used `cmake -H. -Bbuild -G "Unix Makefiles"`.

 * rosdistro: melodic
 * rosversion: 1.14.11

Thank you in advance

**Comment by Innoviz-Tech-Support** [comment]
Thanks for the comment.
To run the ROS example, please run chmod +x for the run_rviz.sh file.

We will also update our instructions to make it clearer.

**Comment by Innoviz-Tech-Support** [comment]
The file now has the correct executable permissions.
Thanks again!
