### ISSUE TITLE
Reading examples with different filenames/structure 

### ISSUE THREAD

**Issue by Yaccoub** [InnovizTechnologies/InnovizAPI#6]
Hello all, 

I noticed that the python example scripts `om_get_frame_example.py` and `om_get_frame_deblooming_example.py` are always looking for specific filenames/structure inside the `Lidar_1.invz4_4` directory (raw data filename must be `09101_000` etc..). Is there is a possibility to read other recordings with different naming/structure(INVZ4_3 for example). Thank you in advance.

**Comment by Innoviz-Tech-Support** [comment]
Hello @Yaccoub,
The two sample scripts you mentioned are actually for getting frame data while connected to a device.  The sample scripts for reading from recordings are `recording_get_frame_deblooming_example.py`, `recording_get_frame_example.py`, and `recording_get_objects.py`, 
Actually, the folder name can be anything you'd like, it does not need to be `Lidar_1.invz4_4`.  When providing the path to the recording, only the directory path is given.  Then the API retrieves all the relevant files from the given directory.  The files themselves (i.e. `09101_000`) should not be renamed, and they all need to be there in order for the API to read them.
