### ISSUE TITLE
Read Pointcloud from PCAP file

### ISSUE THREAD

**Issue by daru91** [InnovizTechnologies/InnovizAPI#7]
Hi, is it possible to parse a point cloud from a PCAP file using the API?

**Comment by Innoviz-Tech-Support** [comment]
Unfortunately this isn't possible at this time.
You'll have to either use an invz recording or be directly connected to a device in order for the API to read the point cloud.
If you have a pcap file you want to parse, please contact our technical support team about this.

**Comment by LDwwh** [comment]
Hello, I have same requirements to parse from pcap files. I load the payloads into [PacketContainer](https://github.com/InnovizTechnologies/InnovizAPI/blob/main/python/include/common_includes/PacketContainer.h) and have no idea about the next step. How the payloads can be parsed into ROS PointCloud2 using your API?

I sended Email to your technical support team, but no response yet. Thanks a lot :)
