### ISSUE TITLE
Failure to connect & power cycle required when connecting to InnovizOne during startup

### ISSUE THREAD

**Issue by trishmapow** [InnovizTechnologies/InnovizAPI#9]
Ubuntu 20.04, ROS noetic, InnovizAPI v5.6.1, Innoviz eConverter + InnovizOne Falcon or Eagle (FW 0.127.6, HW 0.16.12288)
Steps to reproduce:
- Connect lidar to power
- While lidar is starting up (before normal mode), run innoviz_ros.launch,
- or make status request to /datapoints/get
- Wait for lidar to enter normal mode
- Retry launch file

Expected behaviour: connection works when lidar is in normal mode
Actual behaviour: 'failed to get attributes in the specified time'

Killing launch file, roscore, increasing timeout, etc does not work. Lidar and computer have to be power cycled to reconnect. Behaviour is intermittent.

**Comment by Innoviz-Tech-Support** [comment]
Hello @trishmapow,
After confirming the lidar is in Normal mode, the connection still fails?
Can you confirm that when this problem occurs, you are receiving 220-250 Mbps of traffic?

**Comment by trishmapow** [comment]
Hi, yes after the lidar is in Normal mode the connection still fails. There is no traffic because the driver did not even get past the parameter request stage.

**Comment by Innoviz-Tech-Support** [comment]
Hi,
Could be that you are initiating multiple TCP connections? This might cause the connection to the LiDAR to get stuck which then requires a power cycle.
I have tried to repliacte the issue in here, however it performed well and I couldn't observe the issue.
